In [141]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [142]:
df = pd.read_excel('COVID_DS1.xlsx')
X = df.iloc[:,:14].values
y = df.iloc[:,14:].values

In [143]:
print(y[0][1])

1


In [144]:
def make_it_one(y_,c,z):
    for i in range(0,len(y_)):
        if y_[i][c] == 1:
            y_[i][c] = z
        else:
            pass
    return y_

In [145]:
j = make_it_one(y,0,1)
print(j)

[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]

In [146]:
j = make_it_one(y,1,2)
print(j)

[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]

In [147]:
j = make_it_one(y,2,3)
print(j)

[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 3 0]
 [1 0 0 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 3 0]
 [0 0 3 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]

In [148]:
j = make_it_one(y,3,4)
print(j)

[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 3 0]
 [1 0 0 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 4]
 [0 0 0 4]
 [0 0 0 4]
 [0 0 3 0]
 [0 0 3 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 2 0 0]

In [149]:
print(j[0])
def map_it(j_):
    y_re = []
    for i in range(0,len(j_)):
        y_r = j_[i][0] + j_[i][1] + j_[i][2] + j_[i][3]
        y_re.append(y_r)
    return y_re

[0 2 0 0]


In [150]:
#print(map_it(j))
y_ready  = map_it(j)
y_ready = np.array(y_ready)
print(len(y_ready))

226


In [151]:
X_train,X_val,y_train,y_val = train_test_split(X,y_ready,test_size = 0.25)

classifier = CatBoostClassifier()
classifier.fit(X_train,y_train)

Learning rate set to 0.072268
0:	learn: 1.4872758	total: 3.74ms	remaining: 3.74s
1:	learn: 1.4020198	total: 7.87ms	remaining: 3.93s
2:	learn: 1.3136573	total: 11.8ms	remaining: 3.93s
3:	learn: 1.2216137	total: 14.8ms	remaining: 3.68s
4:	learn: 1.1585389	total: 18.9ms	remaining: 3.75s
5:	learn: 1.0816748	total: 29.8ms	remaining: 4.93s
6:	learn: 1.0272868	total: 33.1ms	remaining: 4.7s
7:	learn: 0.9738545	total: 36.3ms	remaining: 4.5s
8:	learn: 0.9232870	total: 39.1ms	remaining: 4.31s
9:	learn: 0.8735992	total: 42ms	remaining: 4.15s
10:	learn: 0.8293709	total: 60.7ms	remaining: 5.46s
11:	learn: 0.7963543	total: 63.6ms	remaining: 5.23s
12:	learn: 0.7629302	total: 66.5ms	remaining: 5.04s
13:	learn: 0.7299963	total: 69.3ms	remaining: 4.88s
14:	learn: 0.6985920	total: 72.1ms	remaining: 4.74s
15:	learn: 0.6630637	total: 75ms	remaining: 4.61s
16:	learn: 0.6406529	total: 77.8ms	remaining: 4.5s
17:	learn: 0.6188469	total: 81ms	remaining: 4.42s
18:	learn: 0.5973741	total: 83.8ms	remaining: 4.33s
1

188:	learn: 0.0516240	total: 717ms	remaining: 3.08s
189:	learn: 0.0512658	total: 720ms	remaining: 3.07s
190:	learn: 0.0510094	total: 723ms	remaining: 3.06s
191:	learn: 0.0505889	total: 726ms	remaining: 3.06s
192:	learn: 0.0502245	total: 729ms	remaining: 3.05s
193:	learn: 0.0498624	total: 737ms	remaining: 3.06s
194:	learn: 0.0497288	total: 740ms	remaining: 3.05s
195:	learn: 0.0493294	total: 743ms	remaining: 3.05s
196:	learn: 0.0488670	total: 746ms	remaining: 3.04s
197:	learn: 0.0485217	total: 749ms	remaining: 3.03s
198:	learn: 0.0482376	total: 767ms	remaining: 3.09s
199:	learn: 0.0478922	total: 771ms	remaining: 3.08s
200:	learn: 0.0475885	total: 773ms	remaining: 3.07s
201:	learn: 0.0471731	total: 776ms	remaining: 3.07s
202:	learn: 0.0467860	total: 779ms	remaining: 3.06s
203:	learn: 0.0464837	total: 782ms	remaining: 3.05s
204:	learn: 0.0463903	total: 784ms	remaining: 3.04s
205:	learn: 0.0460806	total: 787ms	remaining: 3.03s
206:	learn: 0.0459836	total: 789ms	remaining: 3.02s
207:	learn: 

351:	learn: 0.0237488	total: 1.45s	remaining: 2.66s
352:	learn: 0.0236549	total: 1.45s	remaining: 2.65s
353:	learn: 0.0235710	total: 1.45s	remaining: 2.65s
354:	learn: 0.0234773	total: 1.46s	remaining: 2.65s
355:	learn: 0.0234081	total: 1.47s	remaining: 2.66s
356:	learn: 0.0233187	total: 1.47s	remaining: 2.66s
357:	learn: 0.0232304	total: 1.48s	remaining: 2.65s
358:	learn: 0.0231337	total: 1.48s	remaining: 2.64s
359:	learn: 0.0230410	total: 1.48s	remaining: 2.64s
360:	learn: 0.0228994	total: 1.49s	remaining: 2.63s
361:	learn: 0.0228024	total: 1.49s	remaining: 2.63s
362:	learn: 0.0226595	total: 1.49s	remaining: 2.62s
363:	learn: 0.0226113	total: 1.5s	remaining: 2.61s
364:	learn: 0.0225198	total: 1.5s	remaining: 2.61s
365:	learn: 0.0224431	total: 1.5s	remaining: 2.6s
366:	learn: 0.0223603	total: 1.51s	remaining: 2.6s
367:	learn: 0.0222992	total: 1.53s	remaining: 2.64s
368:	learn: 0.0222241	total: 1.54s	remaining: 2.63s
369:	learn: 0.0221084	total: 1.54s	remaining: 2.63s
370:	learn: 0.022

524:	learn: 0.0139737	total: 2.18s	remaining: 1.97s
525:	learn: 0.0139519	total: 2.19s	remaining: 1.97s
526:	learn: 0.0139125	total: 2.2s	remaining: 1.97s
527:	learn: 0.0138810	total: 2.2s	remaining: 1.97s
528:	learn: 0.0138491	total: 2.21s	remaining: 1.96s
529:	learn: 0.0138200	total: 2.21s	remaining: 1.96s
530:	learn: 0.0137975	total: 2.21s	remaining: 1.95s
531:	learn: 0.0137686	total: 2.23s	remaining: 1.96s
532:	learn: 0.0137415	total: 2.23s	remaining: 1.96s
533:	learn: 0.0137109	total: 2.23s	remaining: 1.95s
534:	learn: 0.0136869	total: 2.24s	remaining: 1.94s
535:	learn: 0.0136556	total: 2.24s	remaining: 1.94s
536:	learn: 0.0136228	total: 2.24s	remaining: 1.93s
537:	learn: 0.0135794	total: 2.25s	remaining: 1.93s
538:	learn: 0.0135468	total: 2.25s	remaining: 1.92s
539:	learn: 0.0135102	total: 2.26s	remaining: 1.92s
540:	learn: 0.0134792	total: 2.26s	remaining: 1.92s
541:	learn: 0.0134526	total: 2.27s	remaining: 1.91s
542:	learn: 0.0134240	total: 2.27s	remaining: 1.91s
543:	learn: 0.

726:	learn: 0.0093692	total: 2.91s	remaining: 1.09s
727:	learn: 0.0093545	total: 2.91s	remaining: 1.09s
728:	learn: 0.0093399	total: 2.92s	remaining: 1.08s
729:	learn: 0.0093161	total: 2.92s	remaining: 1.08s
730:	learn: 0.0093037	total: 2.94s	remaining: 1.08s
731:	learn: 0.0092912	total: 2.94s	remaining: 1.08s
732:	learn: 0.0092781	total: 2.94s	remaining: 1.07s
733:	learn: 0.0092643	total: 2.94s	remaining: 1.07s
734:	learn: 0.0092505	total: 2.95s	remaining: 1.06s
735:	learn: 0.0092352	total: 2.95s	remaining: 1.06s
736:	learn: 0.0092175	total: 2.95s	remaining: 1.05s
737:	learn: 0.0092024	total: 2.96s	remaining: 1.05s
738:	learn: 0.0091790	total: 2.96s	remaining: 1.04s
739:	learn: 0.0091642	total: 2.96s	remaining: 1.04s
740:	learn: 0.0091529	total: 2.96s	remaining: 1.04s
741:	learn: 0.0091388	total: 2.97s	remaining: 1.03s
742:	learn: 0.0091268	total: 2.97s	remaining: 1.03s
743:	learn: 0.0091130	total: 2.97s	remaining: 1.02s
744:	learn: 0.0090944	total: 2.98s	remaining: 1.02s
745:	learn: 

892:	learn: 0.0072871	total: 3.48s	remaining: 417ms
893:	learn: 0.0072746	total: 3.48s	remaining: 413ms
894:	learn: 0.0072657	total: 3.49s	remaining: 410ms
895:	learn: 0.0072578	total: 3.51s	remaining: 407ms
896:	learn: 0.0072471	total: 3.51s	remaining: 403ms
897:	learn: 0.0072353	total: 3.51s	remaining: 399ms
898:	learn: 0.0072258	total: 3.52s	remaining: 395ms
899:	learn: 0.0072176	total: 3.52s	remaining: 391ms
900:	learn: 0.0072062	total: 3.52s	remaining: 387ms
901:	learn: 0.0071934	total: 3.52s	remaining: 383ms
902:	learn: 0.0071828	total: 3.53s	remaining: 379ms
903:	learn: 0.0071740	total: 3.53s	remaining: 375ms
904:	learn: 0.0071681	total: 3.53s	remaining: 371ms
905:	learn: 0.0071604	total: 3.54s	remaining: 367ms
906:	learn: 0.0071527	total: 3.54s	remaining: 363ms
907:	learn: 0.0071433	total: 3.54s	remaining: 359ms
908:	learn: 0.0071361	total: 3.55s	remaining: 356ms
909:	learn: 0.0071288	total: 3.56s	remaining: 352ms
910:	learn: 0.0071186	total: 3.56s	remaining: 348ms
911:	learn: 

In [152]:
y_pred  = classifier.predict(X_val)

print(np.concatenate((y_pred.reshape(len(y_pred),1),y_val.reshape(len(y_val),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [4 4]
 [4 2]
 [2 2]
 [1 1]
 [0 0]
 [4 4]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [3 3]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [4 2]
 [3 3]
 [0 0]
 [1 1]
 [4 4]
 [3 3]
 [0 0]
 [3 3]
 [2 2]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [3 3]
 [2 2]]


In [153]:
cm = confusion_matrix(y_val,y_pred)
print(cm)
accuracy_score(y_val,y_pred)

[[22  0  0  0  0]
 [ 0 13  0  0  0]
 [ 0  0 11  0  2]
 [ 0  0  0  6  0]
 [ 0  0  0  0  3]]


0.9649122807017544

In [154]:
accuracy = cross_val_score(estimator = classifier,X = X_train,y = y_train,cv = 5)
print("Accuracy : ",accuracy.mean()*100)
print("Standard Deviation : ",accuracy.std()*100)

Learning rate set to 0.071445
0:	learn: 1.4980291	total: 1.84ms	remaining: 1.83s
1:	learn: 1.4259500	total: 4.87ms	remaining: 2.43s
2:	learn: 1.3411733	total: 8.1ms	remaining: 2.69s
3:	learn: 1.2648330	total: 11.2ms	remaining: 2.78s
4:	learn: 1.1917269	total: 14.9ms	remaining: 2.96s
5:	learn: 1.1418293	total: 17.9ms	remaining: 2.97s
6:	learn: 1.0877867	total: 20.9ms	remaining: 2.96s
7:	learn: 1.0251823	total: 24ms	remaining: 2.97s
8:	learn: 0.9629005	total: 27ms	remaining: 2.97s
9:	learn: 0.9243168	total: 30.2ms	remaining: 2.98s
10:	learn: 0.8739329	total: 32.4ms	remaining: 2.92s
11:	learn: 0.8378235	total: 35.4ms	remaining: 2.92s
12:	learn: 0.7994900	total: 38.6ms	remaining: 2.93s
13:	learn: 0.7595866	total: 41.7ms	remaining: 2.94s
14:	learn: 0.7324924	total: 44.9ms	remaining: 2.95s
15:	learn: 0.7064154	total: 47.9ms	remaining: 2.95s
16:	learn: 0.6776656	total: 50.8ms	remaining: 2.94s
17:	learn: 0.6550892	total: 53.7ms	remaining: 2.93s
18:	learn: 0.6319321	total: 56.5ms	remaining: 2.9

163:	learn: 0.0647519	total: 558ms	remaining: 2.85s
164:	learn: 0.0642771	total: 561ms	remaining: 2.84s
165:	learn: 0.0636677	total: 564ms	remaining: 2.83s
166:	learn: 0.0631452	total: 568ms	remaining: 2.83s
167:	learn: 0.0626937	total: 571ms	remaining: 2.83s
168:	learn: 0.0621219	total: 574ms	remaining: 2.82s
169:	learn: 0.0615694	total: 578ms	remaining: 2.82s
170:	learn: 0.0610362	total: 581ms	remaining: 2.81s
171:	learn: 0.0606228	total: 584ms	remaining: 2.81s
172:	learn: 0.0600851	total: 586ms	remaining: 2.8s
173:	learn: 0.0596879	total: 590ms	remaining: 2.8s
174:	learn: 0.0591580	total: 593ms	remaining: 2.79s
175:	learn: 0.0586995	total: 596ms	remaining: 2.79s
176:	learn: 0.0581907	total: 599ms	remaining: 2.78s
177:	learn: 0.0579194	total: 602ms	remaining: 2.78s
178:	learn: 0.0573127	total: 605ms	remaining: 2.77s
179:	learn: 0.0567423	total: 608ms	remaining: 2.77s
180:	learn: 0.0561350	total: 611ms	remaining: 2.76s
181:	learn: 0.0557155	total: 614ms	remaining: 2.76s
182:	learn: 0.

322:	learn: 0.0266976	total: 1.09s	remaining: 2.28s
323:	learn: 0.0265637	total: 1.09s	remaining: 2.28s
324:	learn: 0.0264631	total: 1.09s	remaining: 2.27s
325:	learn: 0.0263134	total: 1.1s	remaining: 2.27s
326:	learn: 0.0262106	total: 1.1s	remaining: 2.27s
327:	learn: 0.0261306	total: 1.1s	remaining: 2.26s
328:	learn: 0.0259910	total: 1.11s	remaining: 2.25s
329:	learn: 0.0259109	total: 1.11s	remaining: 2.25s
330:	learn: 0.0258284	total: 1.11s	remaining: 2.25s
331:	learn: 0.0257362	total: 1.11s	remaining: 2.24s
332:	learn: 0.0256281	total: 1.12s	remaining: 2.24s
333:	learn: 0.0255297	total: 1.12s	remaining: 2.23s
334:	learn: 0.0254171	total: 1.12s	remaining: 2.22s
335:	learn: 0.0253457	total: 1.12s	remaining: 2.22s
336:	learn: 0.0253075	total: 1.13s	remaining: 2.22s
337:	learn: 0.0252449	total: 1.13s	remaining: 2.21s
338:	learn: 0.0251942	total: 1.13s	remaining: 2.21s
339:	learn: 0.0250617	total: 1.13s	remaining: 2.2s
340:	learn: 0.0249755	total: 1.14s	remaining: 2.2s
341:	learn: 0.024

522:	learn: 0.0144554	total: 1.6s	remaining: 1.46s
523:	learn: 0.0144270	total: 1.61s	remaining: 1.46s
524:	learn: 0.0144011	total: 1.61s	remaining: 1.46s
525:	learn: 0.0143746	total: 1.61s	remaining: 1.45s
526:	learn: 0.0143504	total: 1.61s	remaining: 1.45s
527:	learn: 0.0143164	total: 1.62s	remaining: 1.45s
528:	learn: 0.0142852	total: 1.62s	remaining: 1.44s
529:	learn: 0.0142542	total: 1.62s	remaining: 1.44s
530:	learn: 0.0142232	total: 1.62s	remaining: 1.43s
531:	learn: 0.0141825	total: 1.63s	remaining: 1.43s
532:	learn: 0.0141465	total: 1.63s	remaining: 1.43s
533:	learn: 0.0141161	total: 1.63s	remaining: 1.43s
534:	learn: 0.0140791	total: 1.64s	remaining: 1.42s
535:	learn: 0.0140478	total: 1.64s	remaining: 1.42s
536:	learn: 0.0140180	total: 1.64s	remaining: 1.41s
537:	learn: 0.0139925	total: 1.64s	remaining: 1.41s
538:	learn: 0.0139565	total: 1.65s	remaining: 1.41s
539:	learn: 0.0139301	total: 1.65s	remaining: 1.4s
540:	learn: 0.0138924	total: 1.65s	remaining: 1.4s
541:	learn: 0.0

723:	learn: 0.0099000	total: 2.12s	remaining: 809ms
724:	learn: 0.0098819	total: 2.12s	remaining: 806ms
725:	learn: 0.0098688	total: 2.13s	remaining: 803ms
726:	learn: 0.0098572	total: 2.13s	remaining: 799ms
727:	learn: 0.0098443	total: 2.13s	remaining: 796ms
728:	learn: 0.0098287	total: 2.13s	remaining: 793ms
729:	learn: 0.0098140	total: 2.14s	remaining: 790ms
730:	learn: 0.0097935	total: 2.14s	remaining: 787ms
731:	learn: 0.0097726	total: 2.14s	remaining: 784ms
732:	learn: 0.0097531	total: 2.14s	remaining: 781ms
733:	learn: 0.0097364	total: 2.15s	remaining: 778ms
734:	learn: 0.0097227	total: 2.15s	remaining: 775ms
735:	learn: 0.0097004	total: 2.15s	remaining: 771ms
736:	learn: 0.0096889	total: 2.15s	remaining: 769ms
737:	learn: 0.0096753	total: 2.16s	remaining: 766ms
738:	learn: 0.0096633	total: 2.16s	remaining: 763ms
739:	learn: 0.0096481	total: 2.16s	remaining: 759ms
740:	learn: 0.0096374	total: 2.16s	remaining: 756ms
741:	learn: 0.0096155	total: 2.17s	remaining: 753ms
742:	learn: 

925:	learn: 0.0074694	total: 2.64s	remaining: 211ms
926:	learn: 0.0074580	total: 2.64s	remaining: 208ms
927:	learn: 0.0074494	total: 2.64s	remaining: 205ms
928:	learn: 0.0074409	total: 2.64s	remaining: 202ms
929:	learn: 0.0074317	total: 2.65s	remaining: 199ms
930:	learn: 0.0074246	total: 2.65s	remaining: 196ms
931:	learn: 0.0074165	total: 2.65s	remaining: 193ms
932:	learn: 0.0074101	total: 2.65s	remaining: 191ms
933:	learn: 0.0074024	total: 2.66s	remaining: 188ms
934:	learn: 0.0073913	total: 2.66s	remaining: 185ms
935:	learn: 0.0073840	total: 2.66s	remaining: 182ms
936:	learn: 0.0073771	total: 2.66s	remaining: 179ms
937:	learn: 0.0073697	total: 2.67s	remaining: 176ms
938:	learn: 0.0073619	total: 2.67s	remaining: 173ms
939:	learn: 0.0073545	total: 2.67s	remaining: 171ms
940:	learn: 0.0073477	total: 2.67s	remaining: 168ms
941:	learn: 0.0073355	total: 2.68s	remaining: 165ms
942:	learn: 0.0073271	total: 2.68s	remaining: 162ms
943:	learn: 0.0073174	total: 2.68s	remaining: 159ms
944:	learn: 

101:	learn: 0.1247450	total: 249ms	remaining: 2.19s
102:	learn: 0.1227394	total: 252ms	remaining: 2.19s
103:	learn: 0.1209090	total: 254ms	remaining: 2.19s
104:	learn: 0.1193782	total: 257ms	remaining: 2.19s
105:	learn: 0.1177626	total: 259ms	remaining: 2.18s
106:	learn: 0.1166111	total: 261ms	remaining: 2.18s
107:	learn: 0.1153758	total: 263ms	remaining: 2.17s
108:	learn: 0.1142138	total: 266ms	remaining: 2.17s
109:	learn: 0.1132230	total: 268ms	remaining: 2.17s
110:	learn: 0.1118687	total: 271ms	remaining: 2.17s
111:	learn: 0.1102999	total: 274ms	remaining: 2.17s
112:	learn: 0.1092052	total: 277ms	remaining: 2.17s
113:	learn: 0.1075693	total: 279ms	remaining: 2.17s
114:	learn: 0.1064480	total: 281ms	remaining: 2.16s
115:	learn: 0.1055888	total: 283ms	remaining: 2.16s
116:	learn: 0.1045970	total: 287ms	remaining: 2.16s
117:	learn: 0.1035501	total: 289ms	remaining: 2.16s
118:	learn: 0.1026335	total: 291ms	remaining: 2.16s
119:	learn: 0.1018094	total: 294ms	remaining: 2.16s
120:	learn: 

316:	learn: 0.0298650	total: 763ms	remaining: 1.64s
317:	learn: 0.0296825	total: 766ms	remaining: 1.64s
318:	learn: 0.0295719	total: 768ms	remaining: 1.64s
319:	learn: 0.0294606	total: 770ms	remaining: 1.64s
320:	learn: 0.0293407	total: 772ms	remaining: 1.63s
321:	learn: 0.0292472	total: 775ms	remaining: 1.63s
322:	learn: 0.0291442	total: 777ms	remaining: 1.63s
323:	learn: 0.0290178	total: 779ms	remaining: 1.63s
324:	learn: 0.0289109	total: 781ms	remaining: 1.62s
325:	learn: 0.0288159	total: 784ms	remaining: 1.62s
326:	learn: 0.0287020	total: 787ms	remaining: 1.62s
327:	learn: 0.0286043	total: 790ms	remaining: 1.62s
328:	learn: 0.0284902	total: 792ms	remaining: 1.61s
329:	learn: 0.0283680	total: 794ms	remaining: 1.61s
330:	learn: 0.0282593	total: 796ms	remaining: 1.61s
331:	learn: 0.0280708	total: 798ms	remaining: 1.61s
332:	learn: 0.0279800	total: 801ms	remaining: 1.6s
333:	learn: 0.0278793	total: 804ms	remaining: 1.6s
334:	learn: 0.0278077	total: 806ms	remaining: 1.6s
335:	learn: 0.0

530:	learn: 0.0153716	total: 1.26s	remaining: 1.11s
531:	learn: 0.0153491	total: 1.26s	remaining: 1.11s
532:	learn: 0.0152939	total: 1.26s	remaining: 1.11s
533:	learn: 0.0152618	total: 1.27s	remaining: 1.1s
534:	learn: 0.0152196	total: 1.27s	remaining: 1.1s
535:	learn: 0.0151699	total: 1.27s	remaining: 1.1s
536:	learn: 0.0151408	total: 1.27s	remaining: 1.1s
537:	learn: 0.0151124	total: 1.28s	remaining: 1.1s
538:	learn: 0.0150726	total: 1.28s	remaining: 1.09s
539:	learn: 0.0150437	total: 1.28s	remaining: 1.09s
540:	learn: 0.0150127	total: 1.28s	remaining: 1.09s
541:	learn: 0.0149849	total: 1.29s	remaining: 1.09s
542:	learn: 0.0149589	total: 1.29s	remaining: 1.08s
543:	learn: 0.0149312	total: 1.29s	remaining: 1.08s
544:	learn: 0.0148832	total: 1.29s	remaining: 1.08s
545:	learn: 0.0148501	total: 1.29s	remaining: 1.08s
546:	learn: 0.0148312	total: 1.3s	remaining: 1.07s
547:	learn: 0.0147978	total: 1.3s	remaining: 1.07s
548:	learn: 0.0147672	total: 1.3s	remaining: 1.07s
549:	learn: 0.014731

754:	learn: 0.0099760	total: 1.77s	remaining: 574ms
755:	learn: 0.0099532	total: 1.77s	remaining: 571ms
756:	learn: 0.0099423	total: 1.77s	remaining: 569ms
757:	learn: 0.0099258	total: 1.77s	remaining: 567ms
758:	learn: 0.0099118	total: 1.78s	remaining: 565ms
759:	learn: 0.0098982	total: 1.78s	remaining: 562ms
760:	learn: 0.0098929	total: 1.78s	remaining: 560ms
761:	learn: 0.0098803	total: 1.79s	remaining: 558ms
762:	learn: 0.0098683	total: 1.79s	remaining: 556ms
763:	learn: 0.0098588	total: 1.79s	remaining: 554ms
764:	learn: 0.0098470	total: 1.79s	remaining: 551ms
765:	learn: 0.0098341	total: 1.8s	remaining: 549ms
766:	learn: 0.0098203	total: 1.8s	remaining: 547ms
767:	learn: 0.0098161	total: 1.8s	remaining: 545ms
768:	learn: 0.0097991	total: 1.8s	remaining: 542ms
769:	learn: 0.0097931	total: 1.81s	remaining: 540ms
770:	learn: 0.0097780	total: 1.81s	remaining: 538ms
771:	learn: 0.0097653	total: 1.81s	remaining: 535ms
772:	learn: 0.0097484	total: 1.81s	remaining: 533ms
773:	learn: 0.00

987:	learn: 0.0072842	total: 2.28s	remaining: 27.6ms
988:	learn: 0.0072754	total: 2.28s	remaining: 25.4ms
989:	learn: 0.0072705	total: 2.28s	remaining: 23ms
990:	learn: 0.0072645	total: 2.28s	remaining: 20.7ms
991:	learn: 0.0072569	total: 2.29s	remaining: 18.4ms
992:	learn: 0.0072492	total: 2.29s	remaining: 16.1ms
993:	learn: 0.0072417	total: 2.29s	remaining: 13.8ms
994:	learn: 0.0072323	total: 2.29s	remaining: 11.5ms
995:	learn: 0.0072251	total: 2.29s	remaining: 9.21ms
996:	learn: 0.0072168	total: 2.3s	remaining: 6.91ms
997:	learn: 0.0072089	total: 2.3s	remaining: 4.61ms
998:	learn: 0.0072032	total: 2.3s	remaining: 2.3ms
999:	learn: 0.0071974	total: 2.3s	remaining: 0us
Learning rate set to 0.071445
0:	learn: 1.4958595	total: 2.77ms	remaining: 2.77s
1:	learn: 1.4090588	total: 6.08ms	remaining: 3.03s
2:	learn: 1.3245723	total: 8.89ms	remaining: 2.95s
3:	learn: 1.2504187	total: 11.7ms	remaining: 2.91s
4:	learn: 1.1871591	total: 14.4ms	remaining: 2.86s
5:	learn: 1.1127467	total: 17.1ms	re

179:	learn: 0.0642208	total: 641ms	remaining: 2.92s
180:	learn: 0.0640188	total: 644ms	remaining: 2.91s
181:	learn: 0.0635284	total: 647ms	remaining: 2.91s
182:	learn: 0.0631134	total: 650ms	remaining: 2.9s
183:	learn: 0.0624911	total: 664ms	remaining: 2.94s
184:	learn: 0.0620265	total: 667ms	remaining: 2.94s
185:	learn: 0.0613257	total: 670ms	remaining: 2.93s
186:	learn: 0.0611917	total: 673ms	remaining: 2.92s
187:	learn: 0.0610497	total: 675ms	remaining: 2.92s
188:	learn: 0.0607727	total: 678ms	remaining: 2.91s
189:	learn: 0.0606451	total: 681ms	remaining: 2.9s
190:	learn: 0.0602642	total: 684ms	remaining: 2.9s
191:	learn: 0.0597710	total: 687ms	remaining: 2.89s
192:	learn: 0.0591805	total: 690ms	remaining: 2.88s
193:	learn: 0.0587839	total: 709ms	remaining: 2.94s
194:	learn: 0.0586631	total: 712ms	remaining: 2.94s
195:	learn: 0.0580936	total: 715ms	remaining: 2.93s
196:	learn: 0.0575657	total: 718ms	remaining: 2.92s
197:	learn: 0.0572206	total: 720ms	remaining: 2.92s
198:	learn: 0.0

357:	learn: 0.0271513	total: 1.4s	remaining: 2.51s
358:	learn: 0.0270469	total: 1.4s	remaining: 2.5s
359:	learn: 0.0269315	total: 1.41s	remaining: 2.51s
360:	learn: 0.0268496	total: 1.41s	remaining: 2.5s
361:	learn: 0.0267436	total: 1.42s	remaining: 2.5s
362:	learn: 0.0266524	total: 1.42s	remaining: 2.49s
363:	learn: 0.0265109	total: 1.42s	remaining: 2.49s
364:	learn: 0.0264178	total: 1.44s	remaining: 2.51s
365:	learn: 0.0263218	total: 1.46s	remaining: 2.52s
366:	learn: 0.0261804	total: 1.47s	remaining: 2.54s
367:	learn: 0.0260891	total: 1.48s	remaining: 2.53s
368:	learn: 0.0259665	total: 1.48s	remaining: 2.53s
369:	learn: 0.0258891	total: 1.48s	remaining: 2.52s
370:	learn: 0.0257863	total: 1.49s	remaining: 2.52s
371:	learn: 0.0257029	total: 1.49s	remaining: 2.52s
372:	learn: 0.0255740	total: 1.49s	remaining: 2.51s
373:	learn: 0.0254675	total: 1.5s	remaining: 2.5s
374:	learn: 0.0253628	total: 1.5s	remaining: 2.5s
375:	learn: 0.0252396	total: 1.5s	remaining: 2.49s
376:	learn: 0.0251403	

535:	learn: 0.0160253	total: 2.32s	remaining: 2.01s
536:	learn: 0.0159958	total: 2.32s	remaining: 2s
537:	learn: 0.0159599	total: 2.32s	remaining: 2s
538:	learn: 0.0159501	total: 2.33s	remaining: 1.99s
539:	learn: 0.0159204	total: 2.33s	remaining: 1.99s
540:	learn: 0.0158758	total: 2.33s	remaining: 1.98s
541:	learn: 0.0158407	total: 2.34s	remaining: 1.98s
542:	learn: 0.0157959	total: 2.34s	remaining: 1.97s
543:	learn: 0.0157577	total: 2.35s	remaining: 1.97s
544:	learn: 0.0157166	total: 2.35s	remaining: 1.97s
545:	learn: 0.0156847	total: 2.36s	remaining: 1.96s
546:	learn: 0.0156514	total: 2.38s	remaining: 1.97s
547:	learn: 0.0156148	total: 2.39s	remaining: 1.97s
548:	learn: 0.0155651	total: 2.39s	remaining: 1.96s
549:	learn: 0.0155187	total: 2.39s	remaining: 1.96s
550:	learn: 0.0154914	total: 2.4s	remaining: 1.95s
551:	learn: 0.0154641	total: 2.41s	remaining: 1.96s
552:	learn: 0.0154282	total: 2.43s	remaining: 1.96s
553:	learn: 0.0153966	total: 2.43s	remaining: 1.96s
554:	learn: 0.01535

749:	learn: 0.0105919	total: 3.24s	remaining: 1.08s
750:	learn: 0.0105799	total: 3.24s	remaining: 1.07s
751:	learn: 0.0105649	total: 3.24s	remaining: 1.07s
752:	learn: 0.0105413	total: 3.25s	remaining: 1.06s
753:	learn: 0.0105212	total: 3.25s	remaining: 1.06s
754:	learn: 0.0104983	total: 3.25s	remaining: 1.06s
755:	learn: 0.0104946	total: 3.26s	remaining: 1.05s
756:	learn: 0.0104758	total: 3.26s	remaining: 1.05s
757:	learn: 0.0104611	total: 3.26s	remaining: 1.04s
758:	learn: 0.0104426	total: 3.27s	remaining: 1.04s
759:	learn: 0.0104234	total: 3.27s	remaining: 1.03s
760:	learn: 0.0104101	total: 3.28s	remaining: 1.03s
761:	learn: 0.0103945	total: 3.28s	remaining: 1.02s
762:	learn: 0.0103797	total: 3.28s	remaining: 1.02s
763:	learn: 0.0103635	total: 3.29s	remaining: 1.01s
764:	learn: 0.0103469	total: 3.29s	remaining: 1.01s
765:	learn: 0.0103240	total: 3.29s	remaining: 1s
766:	learn: 0.0103112	total: 3.29s	remaining: 1s
767:	learn: 0.0103020	total: 3.3s	remaining: 996ms
768:	learn: 0.01028

911:	learn: 0.0083913	total: 3.77s	remaining: 364ms
912:	learn: 0.0083815	total: 3.78s	remaining: 360ms
913:	learn: 0.0083715	total: 3.78s	remaining: 356ms
914:	learn: 0.0083608	total: 3.78s	remaining: 352ms
915:	learn: 0.0083476	total: 3.79s	remaining: 347ms
916:	learn: 0.0083370	total: 3.79s	remaining: 343ms
917:	learn: 0.0083240	total: 3.79s	remaining: 339ms
918:	learn: 0.0083128	total: 3.8s	remaining: 335ms
919:	learn: 0.0083035	total: 3.8s	remaining: 331ms
920:	learn: 0.0082971	total: 3.8s	remaining: 326ms
921:	learn: 0.0082851	total: 3.81s	remaining: 322ms
922:	learn: 0.0082753	total: 3.81s	remaining: 318ms
923:	learn: 0.0082651	total: 3.81s	remaining: 314ms
924:	learn: 0.0082572	total: 3.82s	remaining: 309ms
925:	learn: 0.0082471	total: 3.82s	remaining: 305ms
926:	learn: 0.0082367	total: 3.82s	remaining: 301ms
927:	learn: 0.0082290	total: 3.82s	remaining: 297ms
928:	learn: 0.0082190	total: 3.83s	remaining: 293ms
929:	learn: 0.0082116	total: 3.83s	remaining: 288ms
930:	learn: 0.0

71:	learn: 0.1734729	total: 369ms	remaining: 4.75s
72:	learn: 0.1701650	total: 372ms	remaining: 4.72s
73:	learn: 0.1672181	total: 375ms	remaining: 4.7s
74:	learn: 0.1644704	total: 378ms	remaining: 4.66s
75:	learn: 0.1617391	total: 395ms	remaining: 4.8s
76:	learn: 0.1589974	total: 399ms	remaining: 4.78s
77:	learn: 0.1562485	total: 402ms	remaining: 4.75s
78:	learn: 0.1538054	total: 404ms	remaining: 4.71s
79:	learn: 0.1516896	total: 407ms	remaining: 4.68s
80:	learn: 0.1490097	total: 410ms	remaining: 4.65s
81:	learn: 0.1462403	total: 413ms	remaining: 4.63s
82:	learn: 0.1440103	total: 417ms	remaining: 4.6s
83:	learn: 0.1418852	total: 420ms	remaining: 4.58s
84:	learn: 0.1398951	total: 423ms	remaining: 4.55s
85:	learn: 0.1376380	total: 426ms	remaining: 4.53s
86:	learn: 0.1357251	total: 431ms	remaining: 4.52s
87:	learn: 0.1337964	total: 434ms	remaining: 4.49s
88:	learn: 0.1318233	total: 437ms	remaining: 4.48s
89:	learn: 0.1302496	total: 440ms	remaining: 4.45s
90:	learn: 0.1290640	total: 443ms	

254:	learn: 0.0342630	total: 1.3s	remaining: 3.8s
255:	learn: 0.0341233	total: 1.3s	remaining: 3.79s
256:	learn: 0.0339746	total: 1.31s	remaining: 3.78s
257:	learn: 0.0337865	total: 1.33s	remaining: 3.82s
258:	learn: 0.0335919	total: 1.34s	remaining: 3.84s
259:	learn: 0.0334166	total: 1.34s	remaining: 3.83s
260:	learn: 0.0332576	total: 1.35s	remaining: 3.82s
261:	learn: 0.0330776	total: 1.35s	remaining: 3.81s
262:	learn: 0.0328962	total: 1.35s	remaining: 3.8s
263:	learn: 0.0327197	total: 1.36s	remaining: 3.79s
264:	learn: 0.0325671	total: 1.37s	remaining: 3.8s
265:	learn: 0.0324021	total: 1.38s	remaining: 3.8s
266:	learn: 0.0322258	total: 1.38s	remaining: 3.78s
267:	learn: 0.0320465	total: 1.38s	remaining: 3.77s
268:	learn: 0.0319238	total: 1.39s	remaining: 3.76s
269:	learn: 0.0317945	total: 1.39s	remaining: 3.75s
270:	learn: 0.0316634	total: 1.39s	remaining: 3.75s
271:	learn: 0.0315580	total: 1.4s	remaining: 3.73s
272:	learn: 0.0314376	total: 1.4s	remaining: 3.72s
273:	learn: 0.031312

431:	learn: 0.0182772	total: 2.21s	remaining: 2.9s
432:	learn: 0.0182331	total: 2.21s	remaining: 2.9s
433:	learn: 0.0181837	total: 2.22s	remaining: 2.9s
434:	learn: 0.0181343	total: 2.22s	remaining: 2.89s
435:	learn: 0.0180771	total: 2.23s	remaining: 2.88s
436:	learn: 0.0180358	total: 2.23s	remaining: 2.88s
437:	learn: 0.0179941	total: 2.25s	remaining: 2.88s
438:	learn: 0.0179433	total: 2.25s	remaining: 2.88s
439:	learn: 0.0178960	total: 2.25s	remaining: 2.87s
440:	learn: 0.0178510	total: 2.26s	remaining: 2.86s
441:	learn: 0.0178054	total: 2.26s	remaining: 2.85s
442:	learn: 0.0177646	total: 2.26s	remaining: 2.85s
443:	learn: 0.0177185	total: 2.28s	remaining: 2.85s
444:	learn: 0.0176810	total: 2.28s	remaining: 2.85s
445:	learn: 0.0176297	total: 2.3s	remaining: 2.85s
446:	learn: 0.0175645	total: 2.3s	remaining: 2.85s
447:	learn: 0.0175112	total: 2.31s	remaining: 2.85s
448:	learn: 0.0174714	total: 2.33s	remaining: 2.85s
449:	learn: 0.0174253	total: 2.34s	remaining: 2.86s
450:	learn: 0.017

601:	learn: 0.0125315	total: 3.13s	remaining: 2.07s
602:	learn: 0.0125103	total: 3.13s	remaining: 2.06s
603:	learn: 0.0124920	total: 3.14s	remaining: 2.06s
604:	learn: 0.0124603	total: 3.14s	remaining: 2.05s
605:	learn: 0.0124385	total: 3.14s	remaining: 2.04s
606:	learn: 0.0124176	total: 3.14s	remaining: 2.04s
607:	learn: 0.0123869	total: 3.15s	remaining: 2.03s
608:	learn: 0.0123639	total: 3.15s	remaining: 2.02s
609:	learn: 0.0123456	total: 3.15s	remaining: 2.02s
610:	learn: 0.0123277	total: 3.16s	remaining: 2.01s
611:	learn: 0.0123013	total: 3.16s	remaining: 2s
612:	learn: 0.0122829	total: 3.16s	remaining: 2s
613:	learn: 0.0122624	total: 3.16s	remaining: 1.99s
614:	learn: 0.0122345	total: 3.16s	remaining: 1.98s
615:	learn: 0.0122136	total: 3.17s	remaining: 1.97s
616:	learn: 0.0121822	total: 3.17s	remaining: 1.97s
617:	learn: 0.0121637	total: 3.17s	remaining: 1.96s
618:	learn: 0.0121390	total: 3.17s	remaining: 1.95s
619:	learn: 0.0121114	total: 3.18s	remaining: 1.95s
620:	learn: 0.0120

807:	learn: 0.0090199	total: 3.65s	remaining: 868ms
808:	learn: 0.0090096	total: 3.66s	remaining: 863ms
809:	learn: 0.0089981	total: 3.66s	remaining: 858ms
810:	learn: 0.0089875	total: 3.66s	remaining: 853ms
811:	learn: 0.0089765	total: 3.66s	remaining: 848ms
812:	learn: 0.0089618	total: 3.67s	remaining: 843ms
813:	learn: 0.0089501	total: 3.67s	remaining: 838ms
814:	learn: 0.0089403	total: 3.67s	remaining: 833ms
815:	learn: 0.0089276	total: 3.67s	remaining: 828ms
816:	learn: 0.0089174	total: 3.68s	remaining: 823ms
817:	learn: 0.0089072	total: 3.68s	remaining: 818ms
818:	learn: 0.0088948	total: 3.68s	remaining: 814ms
819:	learn: 0.0088841	total: 3.68s	remaining: 809ms
820:	learn: 0.0088716	total: 3.69s	remaining: 804ms
821:	learn: 0.0088596	total: 3.69s	remaining: 799ms
822:	learn: 0.0088474	total: 3.69s	remaining: 794ms
823:	learn: 0.0088328	total: 3.69s	remaining: 789ms
824:	learn: 0.0088216	total: 3.69s	remaining: 784ms
825:	learn: 0.0088110	total: 3.7s	remaining: 779ms
826:	learn: 0

0:	learn: 1.4936781	total: 788us	remaining: 787ms
1:	learn: 1.3969841	total: 5.08ms	remaining: 2.53s
2:	learn: 1.3111062	total: 8.87ms	remaining: 2.95s
3:	learn: 1.2379925	total: 12.4ms	remaining: 3.09s
4:	learn: 1.1740795	total: 16ms	remaining: 3.18s
5:	learn: 1.1230984	total: 19ms	remaining: 3.15s
6:	learn: 1.0542735	total: 22.9ms	remaining: 3.25s
7:	learn: 1.0047942	total: 40.8ms	remaining: 5.05s
8:	learn: 0.9585083	total: 43.9ms	remaining: 4.83s
9:	learn: 0.9146144	total: 47.4ms	remaining: 4.69s
10:	learn: 0.8758311	total: 48.6ms	remaining: 4.37s
11:	learn: 0.8414137	total: 52.3ms	remaining: 4.3s
12:	learn: 0.7980236	total: 72ms	remaining: 5.46s
13:	learn: 0.7698134	total: 74.9ms	remaining: 5.27s
14:	learn: 0.7318044	total: 78ms	remaining: 5.12s
15:	learn: 0.7036876	total: 80.8ms	remaining: 4.97s
16:	learn: 0.6733416	total: 82.6ms	remaining: 4.77s
17:	learn: 0.6469159	total: 87.1ms	remaining: 4.75s
18:	learn: 0.6229439	total: 90.4ms	remaining: 4.67s
19:	learn: 0.6013102	total: 93.5

178:	learn: 0.0603968	total: 741ms	remaining: 3.4s
179:	learn: 0.0599489	total: 744ms	remaining: 3.39s
180:	learn: 0.0595790	total: 748ms	remaining: 3.38s
181:	learn: 0.0592280	total: 752ms	remaining: 3.38s
182:	learn: 0.0585562	total: 772ms	remaining: 3.45s
183:	learn: 0.0580139	total: 776ms	remaining: 3.44s
184:	learn: 0.0576738	total: 779ms	remaining: 3.43s
185:	learn: 0.0571433	total: 782ms	remaining: 3.42s
186:	learn: 0.0567772	total: 784ms	remaining: 3.41s
187:	learn: 0.0563871	total: 803ms	remaining: 3.47s
188:	learn: 0.0559993	total: 806ms	remaining: 3.46s
189:	learn: 0.0555611	total: 809ms	remaining: 3.45s
190:	learn: 0.0552111	total: 818ms	remaining: 3.46s
191:	learn: 0.0547171	total: 821ms	remaining: 3.46s
192:	learn: 0.0543717	total: 824ms	remaining: 3.44s
193:	learn: 0.0540317	total: 827ms	remaining: 3.44s
194:	learn: 0.0537315	total: 830ms	remaining: 3.43s
195:	learn: 0.0534086	total: 833ms	remaining: 3.42s
196:	learn: 0.0531315	total: 836ms	remaining: 3.41s
197:	learn: 0

387:	learn: 0.0222010	total: 1.48s	remaining: 2.33s
388:	learn: 0.0221395	total: 1.48s	remaining: 2.33s
389:	learn: 0.0220567	total: 1.48s	remaining: 2.32s
390:	learn: 0.0220050	total: 1.49s	remaining: 2.32s
391:	learn: 0.0219555	total: 1.49s	remaining: 2.31s
392:	learn: 0.0218952	total: 1.49s	remaining: 2.31s
393:	learn: 0.0218280	total: 1.5s	remaining: 2.3s
394:	learn: 0.0217554	total: 1.5s	remaining: 2.3s
395:	learn: 0.0217068	total: 1.5s	remaining: 2.29s
396:	learn: 0.0216388	total: 1.51s	remaining: 2.29s
397:	learn: 0.0215733	total: 1.51s	remaining: 2.28s
398:	learn: 0.0214797	total: 1.52s	remaining: 2.29s
399:	learn: 0.0214269	total: 1.52s	remaining: 2.29s
400:	learn: 0.0213615	total: 1.53s	remaining: 2.28s
401:	learn: 0.0213065	total: 1.53s	remaining: 2.28s
402:	learn: 0.0212663	total: 1.53s	remaining: 2.27s
403:	learn: 0.0212209	total: 1.54s	remaining: 2.27s
404:	learn: 0.0211528	total: 1.54s	remaining: 2.26s
405:	learn: 0.0210802	total: 1.54s	remaining: 2.25s
406:	learn: 0.021

580:	learn: 0.0136105	total: 2.19s	remaining: 1.58s
581:	learn: 0.0135791	total: 2.2s	remaining: 1.58s
582:	learn: 0.0135525	total: 2.2s	remaining: 1.57s
583:	learn: 0.0135264	total: 2.2s	remaining: 1.57s
584:	learn: 0.0135049	total: 2.21s	remaining: 1.56s
585:	learn: 0.0134799	total: 2.21s	remaining: 1.56s
586:	learn: 0.0134562	total: 2.21s	remaining: 1.56s
587:	learn: 0.0134313	total: 2.21s	remaining: 1.55s
588:	learn: 0.0134069	total: 2.22s	remaining: 1.55s
589:	learn: 0.0133719	total: 2.23s	remaining: 1.55s
590:	learn: 0.0133472	total: 2.23s	remaining: 1.54s
591:	learn: 0.0133198	total: 2.23s	remaining: 1.54s
592:	learn: 0.0132987	total: 2.24s	remaining: 1.53s
593:	learn: 0.0132675	total: 2.24s	remaining: 1.53s
594:	learn: 0.0132445	total: 2.24s	remaining: 1.53s
595:	learn: 0.0132211	total: 2.24s	remaining: 1.52s
596:	learn: 0.0131966	total: 2.25s	remaining: 1.52s
597:	learn: 0.0131650	total: 2.25s	remaining: 1.51s
598:	learn: 0.0131431	total: 2.25s	remaining: 1.51s
599:	learn: 0.0

740:	learn: 0.0102882	total: 2.75s	remaining: 960ms
741:	learn: 0.0102736	total: 2.76s	remaining: 961ms
742:	learn: 0.0102529	total: 2.77s	remaining: 957ms
743:	learn: 0.0102383	total: 2.77s	remaining: 953ms
744:	learn: 0.0102219	total: 2.77s	remaining: 949ms
745:	learn: 0.0102077	total: 2.77s	remaining: 945ms
746:	learn: 0.0101942	total: 2.78s	remaining: 941ms
747:	learn: 0.0101797	total: 2.78s	remaining: 937ms
748:	learn: 0.0101645	total: 2.78s	remaining: 933ms
749:	learn: 0.0101519	total: 2.79s	remaining: 929ms
750:	learn: 0.0101382	total: 2.79s	remaining: 925ms
751:	learn: 0.0101219	total: 2.79s	remaining: 921ms
752:	learn: 0.0101077	total: 2.79s	remaining: 917ms
753:	learn: 0.0100942	total: 2.8s	remaining: 913ms
754:	learn: 0.0100790	total: 2.8s	remaining: 909ms
755:	learn: 0.0100544	total: 2.8s	remaining: 905ms
756:	learn: 0.0100367	total: 2.81s	remaining: 901ms
757:	learn: 0.0100227	total: 2.81s	remaining: 897ms
758:	learn: 0.0100125	total: 2.81s	remaining: 893ms
759:	learn: 0.0

902:	learn: 0.0082075	total: 3.3s	remaining: 355ms
903:	learn: 0.0081962	total: 3.31s	remaining: 351ms
904:	learn: 0.0081838	total: 3.31s	remaining: 348ms
905:	learn: 0.0081745	total: 3.31s	remaining: 344ms
906:	learn: 0.0081647	total: 3.32s	remaining: 340ms
907:	learn: 0.0081554	total: 3.32s	remaining: 336ms
908:	learn: 0.0081455	total: 3.32s	remaining: 333ms
909:	learn: 0.0081367	total: 3.33s	remaining: 329ms
910:	learn: 0.0081256	total: 3.33s	remaining: 325ms
911:	learn: 0.0081176	total: 3.33s	remaining: 322ms
912:	learn: 0.0081083	total: 3.33s	remaining: 318ms
913:	learn: 0.0080996	total: 3.34s	remaining: 314ms
914:	learn: 0.0080906	total: 3.35s	remaining: 311ms
915:	learn: 0.0080816	total: 3.35s	remaining: 307ms
916:	learn: 0.0080702	total: 3.35s	remaining: 303ms
917:	learn: 0.0080555	total: 3.35s	remaining: 300ms
918:	learn: 0.0080448	total: 3.36s	remaining: 296ms
919:	learn: 0.0080336	total: 3.36s	remaining: 292ms
920:	learn: 0.0080231	total: 3.36s	remaining: 289ms
921:	learn: 0

In [156]:
cds = [[70,99.2,1,1,0,1,0,1,0,0,0,1,1,1]]
cds1= [[70,98.2,0,0,0,1,0,1,0,0,0,1,0,0]]
#[1]corona, [2]cold, [3]fever, [4]flu
print(classifier.predict(cds))

[[1]]


In [157]:
classifier.save_model("Cat_ready",
           format="cbm",
           export_parameters=None,
           pool=None)